// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhaVjB04DKALgS1m7Jsgzcvf_W3WuiRs',
    appId: '1:1012054407867:web:45ef269180696bb387079e',
    messagingSenderId: '1012054407867',
    projectId: 'ydiary-517bb',
    authDomain: 'ydiary-517bb.firebaseapp.com',
    storageBucket: 'ydiary-517bb.firebasestorage.app',
    measurementId: 'G-YVBRXBP308',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0geuPZRWZQoVDh2vCcP-ZSimZHg16BW8',
    appId: '1:1012054407867:ios:19bb950e94903bf787079e',
    messagingSenderId: '1012054407867',
    projectId: 'ydiary-517bb',
    storageBucket: 'ydiary-517bb.firebasestorage.app',
    iosClientId: '1012054407867-idee53pbkvn9ugoajf3qi58d45hehfu1.apps.googleusercontent.com',
    iosBundleId: 'jp.co.sonrisa.ydiary',
  );
}
